#!/usr/bin/env bash
# Bash script that will display information about subdomains.
declare -a Subdomain=("www" "lb-01" "web-01" "web-02")
if (($# == 1))
then
    for val in "${Subdomain[@]}"
    do
        echo -n "The subdomain $val is a "
        dig "$val.$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}' | tail -1 
        echo -n " record and points to "
        dig "$val.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tail -1
    done
else
    echo -n "The subdomain $2 is a "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}' | tail -1
    echo -n " record and points to "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tail -1
fi
