#!/usr/bin/env bash
# world wide web

if [ $# -eq 1 ]
then
    domain_list="www lb-01 web-01 web-02"
else
    domain_list=$2
fi

for subdomain in $domain_list
do
    echo -n "The subdomain $subdomain "
    dig "$subdomain.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{ print "is a " $4 " record and points to " $5}'
done
