#!/usr/bin/env bash
# displays Holberton School 10 timesbut for the 9th iteration, displays Holberton School and then Hi on a new line.
i=1
while [ $i -le 10 ]
do
    if [ $i -ne 9 ]
    then
	echo "Holberton School"
    else
	echo -e "Holberton School\nHi"
    fi
    i=$((i + 1))
done
